---
# Main Ansible variables of user specific GnuPG setup
# ===================================================
# Tim Friske <me@tifr.de>

user_dir: "{{ ansible_env.HOME }}"

bin_dir: "{{ user_dir }}/.local/bin"

gnupg_dir: "{{ user_dir }}/.gnupg"
